spring:
  application:
    name: MyProject02


  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##dbuser
    password: 1111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.myproject02.*.vo

jwt:
  secret: mys2ecretmysec2retmysecr3etmysec
  access-token-validity: 30000    #(1000 * 60 * 5) 5분
  refresh-token-validity: 86400000 #(1000 * 60 * 60 * 24) 1일

